language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-chalkboard' ]; then cd .. && eval "mv $currentfolder generator-chalkboard" && cd generator-chalkboard; fi
